### ISSUE TITLE
VMR build break: sourcelink CS0162 "Unreachable code detected" on internal/release/10.0.3xx

### ISSUE THREAD

**Issue by joeloff** [dotnet/dotnet#7931]
## Summary

The **VMR Source-Only Build** stage in [Source Build Unified Build (1330)](https://dev.azure.com/dnceng/internal/_build?definitionId=1330) fails building `sourcelink` on `internal/release/10.0.3xx`. A `CS0162: Unreachable code detected` warning is treated as an error and fails the build on all RIDs.

## Error

```
src/sourcelink/src/Common/AzureDevOps/AzureDevOpsUrlParser.cs(165,13):
  error CS0162: (NETCORE_ENGINEERING_TELEMETRY=Build) Unreachable code detected
```

Fails across win-x86, win-arm64, linux-x64, linux-arm64 (cross), and alpine legs — i.e. every `sourcelink` build invocation.

Additionally observed (restore, same build):
```
src/msbuild/src/Tasks/Microsoft.Build.Tasks.csproj: error NU1903:
  Package 'System.Security.Cryptography.Xml' 10.0.3 has a known high severity vulnerability
  (GHSA-37gx-xxp4-5rgx, GHSA-w3x6-4m5h-cxqf)
```

## Affected build

| Build | Branch | Detail |
|-------|--------|--------|
| [3027021](https://dev.azure.com/dnceng/internal/_build/results?buildId=3027021) | internal/release/10.0.3xx | sourcelink `CS0162` on all legs; `NU1903` advisory on `System.Security.Cryptography.Xml 10.0.3` |

## Analysis

`AzureDevOpsUrlParser.cs:165` contains an unreachable branch. Because source-build compiles with warnings-as-errors, this blocks the entire VMR build on `internal/release/10.0.3xx`. This is a code fix (not transient) and will not clear on retry.

## Suggested next steps

- Fix `AzureDevOpsUrlParser.cs` to remove/guard the unreachable code at line 165 (backport to the 10.0.3xx sourcelink).
- Separately, address the `System.Security.Cryptography.Xml 10.0.3` high-severity advisory (`NU1903`).

_Filed automatically by build-duty triage (sourcebuild-monitor config), run 2026-07-23._

**Comment by mthalman** [comment]
Moving to dotnet/dotnet as this is not specific to source-build.

**Comment by tmat** [comment]
Fixed by https://dev.azure.com/dnceng/internal/_git/dotnet-dotnet/pullrequest/63187
