### PR TITLE
Reset Razor to main

### PR DESCRIPTION
**Pull request by jjonescz**
Ran `darc vmr reset razor:64fdc2c3d168168a2fa28da45084145eb2be0f4d` locally.

### CODE REVIEW

**Comment by jjonescz** [comment]
RazorSdk build is broken due to changes from https://github.com/dotnet/razor/pull/12258 - @DustinCampbell, can you please take a look?

<p><samp>
/__w/1/s/src/sdk/src/RazorSdk/Tool/GenerateCommand.cs(432,72): error CS0535: 'GenerateCommand.StaticTagHelperFeature' does not implement interface member 'ITagHelperFeature.GetDescriptors(CancellationToken)' [/__w/1/s/src/sdk/src/RazorSdk/Tool/Microsoft.NET.Sdk.Razor.Tool.csproj]
</samp></p>

**Comment by DustinCampbell** [comment]
> RazorSdk build is broken due to changes from [dotnet/razor#12258](https://github.com/dotnet/razor/pull/12258) - @DustinCampbell, can you please take a look?
> 
> /__w/1/s/src/sdk/src/RazorSdk/Tool/GenerateCommand.cs(432,72): error CS0535: 'GenerateCommand.StaticTagHelperFeature' does not implement interface member 'ITagHelperFeature.GetDescriptors(CancellationToken)' [/__w/1/s/src/sdk/src/RazorSdk/Tool/Microsoft.NET.Sdk.Razor.Tool.csproj]

Yup! I was waiting for this change to flow but it was backed up by something else.

**Comment by DustinCampbell** [comment]
@jjonescz: I pushed a fix to your branch for the PR.

**Comment by jjonescz** [comment]
Thanks! That was a simple change :)

**Comment by premun** [comment]
@jjonescz thanks, I will have to merge this on red as that validation step is supposed to be red
